//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartitionQuest.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Display {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Display() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PartitionQuest.UI.Resources.Display", typeof(Display).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только положительные числа.
        /// </summary>
        internal static string BasicPuzzle {
            get {
                return ResourceManager.GetString("BasicPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только нечетные числа.
        /// </summary>
        internal static string CombinationOdd {
            get {
                return ResourceManager.GetString("CombinationOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только уникальные числа.
        /// </summary>
        internal static string DistinctPuzzle {
            get {
                return ResourceManager.GetString("DistinctPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такое разбиение уже было введено!.
        /// </summary>
        internal static string DuplicatePartition {
            get {
                return ResourceManager.GetString("DuplicatePartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный ввод..
        /// </summary>
        internal static string ErrorInput {
            get {
                return ResourceManager.GetString("ErrorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без использования числа {0}..
        /// </summary>
        internal static string ExcludePuzzle {
            get {
                return ResourceManager.GetString("ExcludePuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, есть ошибки. Вот правильные разбиения:.
        /// </summary>
        internal static string FailureHeader {
            get {
                return ResourceManager.GetString("FailureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игра завершена! Ваш итоговый счет: {0} из {1}.
        /// </summary>
        internal static string FinalScore {
            get {
                return ResourceManager.GetString("FinalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разбейте на {0} чисел..
        /// </summary>
        internal static string FixedLengthPuzzle {
            get {
                return ResourceManager.GetString("FixedLengthPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только нечетные числа.
        /// </summary>
        internal static string OddOnlyPuzzle {
            get {
                return ResourceManager.GetString("OddOnlyPuzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разбиение {0} не соответствует условиям задачи!.
        /// </summary>
        internal static string PartitionInvalid {
            get {
                return ResourceManager.GetString("PartitionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разбиение #{0}:.
        /// </summary>
        internal static string PartitionNumber {
            get {
                return ResourceManager.GetString("PartitionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущая сумма: {0}. Осталось: {1}.
        /// </summary>
        internal static string PartitionPrompt {
            get {
                return ResourceManager.GetString("PartitionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задание {0}, возможных разбиений: {1}.
        /// </summary>
        internal static string PuzzleHeader {
            get {
                return ResourceManager.GetString("PuzzleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляем! Все разбиения верны..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
